# Full Stack Open exercise 11.5 -
name: fso-pokedex-pipe

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

env: 
  DEPLOY: ${{ github.event_name == 'push' && ! contains(toJSON(github.event.commits.*.message), '#skip') }}
  
jobs:
  env_var: # workaround for env not being available in job context
    name: Expose DEPLOY to job context
    runs-on: ubuntu-latest
    outputs:
      deploy: ${{ env.DEPLOY }}
    steps:
      - run: echo "exposing env var DEPLOY=$DEPLOY"

  e2e-test:
    uses: ./.github/workflows/playwright.yml

  unit-test:
    uses: ./.github/workflows/lint_test.yml

  deploy:    
    needs: [env_var, unit-test, e2e-test]
    name: Deploy if ${{ needs.env_var.outputs.deploy }}
    if: needs.env_var.outputs.deploy == 'true'
    uses: ./.github/workflows/fly-deploy.yml
    secrets: 
      token: ${{ secrets.FLY_API_TOKEN }}
  
  tag_release:
    needs: [env_var, deploy]
    name: tag if ${{ needs.env_var.outputs.deploy }}
    if: needs.env_var.outputs.deploy == 'true'
    uses: ./.github/workflows/tag_release.yml

  notify:
    needs: [deploy, tag_release]
    name: Send build notification to Discord
    runs-on: ubuntu-latest
    steps:
    - uses: rjstone/discord-webhook-notify@v2
      with:
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
        username: vodedex build bot
        severity: info
        details: New build releases succesfully.