# Full Stack Open exercise 11.5 -
name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

env: 
  DEPLOY: ${{ github.event_name == 'push' && ! contains(toJSON(github.event.commits.*.message), '#skip') }}
  
jobs:
  env_var:
    name: Expose DEPLOY to job context
    runs-on: ubuntu-latest
    outputs:
      deploy: ${{ env.DEPLOY }}
    steps:
      - run: echo "exposing env var DEPLOY=$DEPLOY"

  e2e-test:
    if: false
    uses: ./.github/workflows/playwright.yml

  unit-test:
    uses: ./.github/workflows/lint_test.yml

  deploy:    
    needs: [env_var, unit-test, e2e-test]
    if: false
    uses: ./.github/workflows/fly-deploy.yml
    secrets: 
      token: ${{ secrets.FLY_API_TOKEN }}
  
  tag_release:
    needs: [env_var, unit-test]
    name: tag if ${{ needs.env_var.outputs.deploy }}
    if: needs.env_var.outputs.deploy == 'true'
    uses: ./.github/workflows/tag_release.yml
    