# Full Stack Open exercise 11.5 -
name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

env: 
  DEPLOY: ${{ github.event_name == 'push' && ! contains(toJSON(github.event.commits.*.message), '#skip') }}
  
jobs:
  e2e-test:
    uses: ./.github/workflows/playwright.yml

  unit-test:
    uses: ./.github/workflows/lint_test.yml

  deploy:    
    needs: [unit-test, e2e-test]
    uses: ./.github/workflows/fly-deploy.yml

  tag_release:
    needs: [deploy]
    uses: ./.github/workflows/tag_release.yml
    