name: Testing stuff

on:
  push:
    branches:
      - dev

jobs:
  a_test_job:
    runs-on: ubuntu-latest
    
    steps:
      - name: skip truthy
        run: echo ${{ contains(toJSON(github.event.commits.*.message), '#skip') }}
      - name: skip message
        run: echo ${{ toJSON(github.event.commits.*.message) }}
