name: Testing stuff

on:
  push:
    branches:
      - dev

jobs:
  a_test_job:
    runs-on: ubuntu-latest
    if: ! ${{ contains(toJSON(github.event.commits.*.message), '#skip') }}
    steps:
      - name: skip truthy
        run: echo ${{ contains(toJSON(github.event.commits.*.message), '#skip') }}
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"