name: Testing stuff

on:
  push:
    branches:
      - dev

jobs:
  a_test_job:
    runs-on: ubuntu-latest
    
    steps:
      - name: skip message
        run: echo ${{ github.event.commits.*.message }}
