name: Testing stuff

on:
  push:
    branches:
      - dev

jobs:
  a_test_job:
    if: contains(github.event.commits.*.message, '#skip')
    runs-on: ubuntu-latest
    
    steps:
      - name: skip message
        run: echo "Skippin deployment requested ${{ github.event.commits.*.message }}""
